### ユーザー情報取得
GET  http://localhost:8000/api/users/show
Accept:  application/json
Authorization: Bearer 1|4UPxfsbhSyvGoyCo0Qqxs5rDxNZE4lAbKnDhTgcrd1361697

### ユーザー登録
POST http://ge202405.japaneast.cloudapp.azure.com/api/users/store
Content-Type: application/json
Accept: application/json

{
    "name": "jobi"
}
### ユーザー更新
POST  http://ge202405.japaneast.cloudapp.azure.com/api/users/update
Content-Type: application/json
Accept:  application/json
Authorization: Bearer 1|t4ELYO8Jw6p0IpT9dpXJ0obMo73OvxV75p2V4YUac51f01f1

{
    "name" : "aiu"
}
###
POST  http://localhost:8000/api/users/store-title
Content-Type: application/json
Accept:  application/json
Authorization: Bearer 2|BiFtPIki6OYhbSS9HhVy5DFCuGVxhYePhC8TTE00e13d0727

{
    "title_id": 5
}

###
GET  http://localhost:8000/api/users/show-title
Accept:  application/json
Authorization: Bearer 2|BiFtPIki6OYhbSS9HhVy5DFCuGVxhYePhC8TTE00e13d0727
###
POST  http://localhost:8000/api/users/store-friend-request
Content-Type: application/json
Accept:  application/json
Authorization: Bearer 2|BiFtPIki6OYhbSS9HhVy5DFCuGVxhYePhC8TTE00e13d0727

{
    "recipient_id": 101
}
###
GET  http://localhost:8000/api/users/show-friend-request
Accept:  application/json
Authorization: Bearer 1|4UPxfsbhSyvGoyCo0Qqxs5rDxNZE4lAbKnDhTgcrd1361697
###
POST  http://localhost:8000/api/users/store-friend
Content-Type: application/json
Accept:  application/json
Authorization: Bearer 1|4UPxfsbhSyvGoyCo0Qqxs5rDxNZE4lAbKnDhTgcrd1361697

{
    "requesting_user_id": 102
}
###
GET  http://localhost:8000/api/users/show-friend
Accept:  application/json
Authorization: Bearer 1|4UPxfsbhSyvGoyCo0Qqxs5rDxNZE4lAbKnDhTgcrd1361697
###
POST  http://localhost:8000/api/users/stamina-changes-by-reasons
Content-Type: application/json
Accept:  application/json
Authorization: Bearer 1|upFcZfh8NNEmu1zzVYu1UXlDNZ6Q1d7Y244vcYZgab764d0b

{
    "reason_id": 2
}
###
POST  http://localhost:8000/api/users/stamina-auto-recovery
Content-Type: application/json
Accept:  application/json
Authorization: Bearer 1|4UPxfsbhSyvGoyCo0Qqxs5rDxNZE4lAbKnDhTgcrd1361697
###
POST  http://localhost:8000/api/users/provider-stamina
Content-Type: application/json
Accept:  application/json
Authorization: Bearer 1|4UPxfsbhSyvGoyCo0Qqxs5rDxNZE4lAbKnDhTgcrd1361697

{
    "friend_id": 102
}
###
GET  http://localhost:8000/api/stages/show-stage
Accept:  application/json
Authorization: Bearer 2|SoyyDnscs9soJk1Aa0rjowkiu5o0fnjybwf70TaX6e754666
###
POST  http://localhost:8000/api/stages/clear-stage
Content-Type: application/json
Accept:  application/json
Authorization: Bearer 1|4UPxfsbhSyvGoyCo0Qqxs5rDxNZE4lAbKnDhTgcrd1361697

{
    "stage_id": 3,
    "evaluation": 3,
    "collectibles": 1
}
###
POST  http://localhost:8000/api/stages/getCells
Content-Type: application/json
Accept:  application/json

{
    "stage_id": 1
}
###

GET  http://ge202405.japaneast.cloudapp.azure.com/api/tests
